<a href="https://colab.research.google.com/github/kanishk51/BI-assignments-/blob/main/LabEval_MCA1_202301028.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Multiply the following matrices and also find covariance between matrices using
#Numpy:i. p = [1,2],[2,3]]q=[[4,5],[6,7]]

import numpy as np

p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])

product = np.dot(p, q)
print("Matrix Product of the given matrices:")
print(product)

covariance = np.cov(p, q)
print("\nCovariance between 2 matrices:")
print(covariance)


Matrix Product of the given matrices:
[[16 19]
 [26 31]]

Covariance between 2 matrices:
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]
